#!/usr/bin/env python3

# Module grabs the CSV version of a Google Sheet. Only tested with a simple one
# page spreadsheet, generated by a Google Form.

# Adapted from this stack overflow answer: https://stackoverflow.com/a/18296318
# Additional notes:
# - The generated API key will have an associated email. Share your Google Sheet doc
#   with this email address (if you don't want to make the doc public...)

from argparse import ArgumentParser, Namespace

import csv
import gspread
from oauth2client.service_account import ServiceAccountCredentials


def main(args=None, keyfile=None, save_file=None):
    if args is None:
        if not keyfile:
            raise RuntimeError(f"Must provide a keyfile when calling {__file__}.main()")
        args = Namespace()
        args.keyfile=keyfile
    
    scope = ['https://spreadsheets.google.com/feeds']
    credentials = ServiceAccountCredentials.from_json_keyfile_name(args.keyfile, scope)

    # docid can be taken from the URL
    docid = "19QzjkwWr0bPhGUIiW4W2drG1AlmEcrCx5tFkHHAgrb8" # Form responses doc (private)

    client = gspread.authorize(credentials)
    spreadsheet = client.open_by_key(docid)
    for i, worksheet in enumerate(spreadsheet.worksheets()):
        if save_file is None:
            save_file = docid + '-worksheet' + str(i) + '.csv'
        with open(save_file, 'w') as f:
            writer = csv.writer(f)
            writer.writerows(worksheet.get_all_values())
        print(f"got {save_file}")


if __name__ == '__main__':
    parser = ArgumentParser()
    parser.add_argument("keyfile", action='store',
                        help="TODO")
    args = parser.parse_args()
    main(args)
